FROM python:3.8-slim-buster

WORKDIR /app
COPY . .
RUN pip3 install -r requirements.txt

# CMD python3 environment/database_objects/user.py; python3 environment/database_objects/project.py; python3 environment/database_objects/task.py
CMD python3 environment/database_objects/task.py